### PR TITLE
Add integration tests

### PR DESCRIPTION
**Pull request by danog**
Reverts davidcole1340/ext-php-rs#293

### CODE REVIEW

**Comment by danog** [comment]
Don't have a mac os machine so can't easily debug the mac os failures, would be really happy if someone could give a try...

**Comment by joehoyle** [comment]
Oh I see why it's only being triggered on the Debug build, it seems this check is only made for internal functions if ZEND_EDBUG:

```c
#if ZEND_DEBUG
static ZEND_COLD void zend_verify_internal_return_error(const zend_function *zf, zval *value)
{
	...

static ZEND_COLD void zend_verify_void_return_error(const zend_function *zf, const char *returned_msg, const char *returned_kind)
{
	...
}

static bool zend_verify_internal_return_type(zend_function *zf, zval *ret)
{
	...
}
#endif
```

**Comment by joehoyle** [comment]
Yeah I'd imagine we should be running all the test envs with a debug build in that case. i think you may be able to reproduce if run you against a debug build on linux?

**Comment by joehoyle** [comment]
FYI we are setting the PHP build to debug on macos here: https://github.com/davidcole1340/ext-php-rs/blob/master/.github/workflows/build.yml#L48

**Comment by danog** [comment]
>Oh I see why it's only being triggered on the Debug build, it seems this check is only made for internal functions if ZEND_EDBUG:
> think you may be able to reproduce if run you against a debug build on linux?

Indeed, I encountered the exact same issue previously on a linux debug build, which lead to the discovery of a bug in ZendType (a simple C string was used instead of a zend string for the type name), which I fixed in https://github.com/davidcole1340/ext-php-rs/commit/86c9074470a8e1ea4742eadde026159ede7e7528, but then the same issue started occurring again here, only on Mac OS builds, and not on a local Linux debug build (which has different issues, namely https://github.com/davidcole1340/ext-php-rs/issues/290 + a segfault when running library tests probably due to memory corruption as for #290).

>FYI we are setting the PHP build to debug on macos here: https://github.com/davidcole1340/ext-php-rs/blob/master/.github/workflows/build.yml#L48

Actually shouldn't that enable debug builds for all OSes?

**Comment by joehoyle** [comment]
Hmm ok I think https://github.com/davidcole1340/ext-php-rs/commit/86c9074470a8e1ea4742eadde026159ede7e7528#diff-758fcaf4f7ca5c65a01fb257423dc04af5d266f93547a89f2559bec5410b2f1aL85 might be the key. To also test this I can do:

```php
$r = new ReflectionFunction('test_class');
var_dump( $r->getReturnType()->getName() );
```

That gives me `string(1) ""` which I think is the corrupt. When I change it back to a CString `ptr: CString::new(class_name).ok()?.into_raw() as *mut c_void,` then I get the correct return type:

```php
string(9) "TestClass"
```

**Comment by danog** [comment]
The issue was caused by the fact that php 8.2 and below want a C string in the arginfo to then convert it internally to a zend string, but php 8.3 wants a C string only if the literal flag is set, and a zend string otherwise.

**Pull request merged**
