### PR TITLE
Add support for Zval IS_INDIRECT

### PR DESCRIPTION
**Pull request by joehoyle**
As mentioned in #219, I believe we're making incorrect use of IS_CALLABLE on Zval types right now. Zval type bits are never actually stored as IS_CALLABLE, which overlaps with the _actual_ type value of IS_INDIRECT. IS_INDIRECT is almost the same as IS_REFERENCE, but is a direct reference to another Zval rather than reference object. As `Zval::is_callable()` and `Zval::callable()` don't actually make use of `IS_CALLABLE` then I think it's safe to switch this out.

### CODE REVIEW

**Comment by ptondereau** [comment]
@joehoyle can you please rebase?

**Comment by joehoyle** [comment]
Ok fixed merge conflicts

**Comment by danog** [comment]
Could you please rebase?

**Comment by joehoyle** [comment]
Ok rebazed

**Pull request merged**
