### PR TITLE
Allow passing `--yes` parameter to bypass prompts

### PR DESCRIPTION
**Pull request by roborourke**
Makes this tool usable in automated builds such as Docker containers.

Addresses https://github.com/davidcole1340/ext-php-rs/issues/133

### CODE REVIEW

**Comment by roborourke** [comment]
Sorry for the delay - updated the readme and the guide now.

**Comment by TobiasBengtsson** [comment]
Could you try re-basing on the latest `master`? :pray: I think the build will become green then

**Comment by davidcole1340** [comment]
Thanks!

**Comment by estk** [comment]
@here can we get a new release on crates.io?

**Comment by davidcole1340** [comment]
Released as v0.8.1

**Pull request merged**
