### PR TITLE
Add StreamWrapper API

### PR DESCRIPTION
**Pull request by joehoyle**
This allows extensions to register and unregister custom stream wrappers

Still need to add docs.

### CODE REVIEW

**Comment by danog** [comment]
Looks awesome, could you take a look at the clippy failures though? :)

**Comment by joehoyle** [comment]
Ah this had `process-globals` as the upstream as it relied on some of that stuff. I think it might be better to revert this merge into `process-globals` as this is failing quite a few clippy checks. We can then put it in draft

**Comment by danog** [comment]
I've already fixed everything, no need to revert

**Comment by joehoyle** [comment]
Ok nice one

**Pull request merged**
